//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogSet
    {
        public int Id { get; set; }
        public int Time { get; set; }
        public string Client { get; set; }
        public string Event { get; set; }
        public string Window { get; set; }
        public string Operation { get; set; }
        public int TimeNeeded { get; set; }
    }
}
