//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WindowSet
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string UnavailableOperation { get; set; }
        public string CurrentClient { get; set; }
        public Nullable<int> RestOfTime { get; set; }
    }
}
